"""empty message

Revision ID: 06be0a1c50d7
Revises: 
Create Date: 2020-07-12 18:13:38.950683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06be0a1c50d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations')
    # ### end Alembic commands ###
