"""empty message

Revision ID: 2ac8c58db89a
Revises: 57d6019fa2ac
Create Date: 2020-07-14 00:18:18.486490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac8c58db89a'
down_revision = '57d6019fa2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('userID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'author', 'author', ['userID'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.drop_column('author', 'userID')
    # ### end Alembic commands ###
