"""empty message

Revision ID: 873b05e6f5c8
Revises: 038898ceaf4e
Create Date: 2020-08-02 02:37:53.021083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873b05e6f5c8'
down_revision = '038898ceaf4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=30), nullable=False))
    op.drop_constraint('user_emailAddress_key', 'user', type_='unique')
    op.drop_column('user', 'emailAddress')
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'passwordHash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('passwordHash', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('emailAddress', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_emailAddress_key', 'user', ['emailAddress'])
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
