"""empty message

Revision ID: ae7f4194e1e1
Revises: 2ac8c58db89a
Create Date: 2020-07-17 01:13:52.008225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7f4194e1e1'
down_revision = '2ac8c58db89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('author_userID_fkey', 'author', type_='foreignkey')
    op.drop_column('author', 'userID')
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['parent_id'], ['id'])
    op.drop_column('comments', 'userID')
    op.drop_column('comments', 'postID')
    op.add_column('posts', sa.Column('authorP_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'author', ['authorP_id'], ['id'])
    op.drop_column('posts', 'authorID')
    op.add_column('users', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'author', ['author_id'], ['id'])
    op.drop_column('users', 'authorID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'author_id')
    op.add_column('posts', sa.Column('authorID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'authorP_id')
    op.add_column('comments', sa.Column('postID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    op.add_column('author', sa.Column('userID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('author_userID_fkey', 'author', 'author', ['userID'], ['id'])
    op.drop_column('author', 'user_id')
    # ### end Alembic commands ###
